# Task 3X3 Matrix

In [1]:
import numpy as np

arr = np.arange(2, 11)
matrix = arr.reshape(3,3)
matrix = matrix.astype(float)

flat = matrix.reshape(-1)

print("Matrix:\n", matrix)
print("Flattened:", flat)
print("Maximum:", np.max(flat))
print("Minimum:", np.min(flat))

Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum: 10.0
Minimum: 2.0
